config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  mount Maestrano::Connector::Rails::Engine, at: '/'

  namespace :webhooks do
    post ':entity/:type/:org_uid' => :receive
  end

  # root 'home#index'
  root 'home#index'
  get 'home/index' => 'home#index'
  get 'home/redirect_to_external' => 'home#redirect_to_external'
  put 'home/update' => 'home#update'
  post 'home/synchronize' => 'home#synchronize'
  get 'synchronizations/index' => 'synchronizations#index'
  get 'shared_entities/index' => 'shared_entities#index'
  get 'admin/delete_webhooks' => 'home#delete_webhooks'


  match 'auth/:provider/request', to: 'oauth#request_omniauth', via: [:get, :post]
  match 'auth/:provider/callback', to: 'oauth#create_omniauth', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  match 'signout_omniauth', to: 'oauth#destroy_omniauth', as: 'signout_omniauth', via: [:get, :post]

  # Sidekiq Admin
  require 'sidekiq/web'
  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    ENV['SIDEKIQ_USERNAME'].present? &
    ActiveSupport::SecurityUtils.secure_compare(username, ENV['SIDEKIQ_USERNAME']) &
    ActiveSupport::SecurityUtils.secure_compare(password, ENV['SIDEKIQ_PASSWORD'])
  end
  mount Sidekiq::Web => '/sidekiq'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def update
    return redirect_to(:back) unless is_admin

    # Update list of entities to synchronize
    current_organization.synchronized_entities.keys.each do |entity|
      current_organization.synchronized_entities[entity][:can_push_to_connec] = params[entity.to_s]["to_connec"] == "1"
      current_organization.synchronized_entities[entity][:can_push_to_external] = params[entity.to_s]["to_external"] == "1"
    end

    full_sync = params['historical-data'].present? && !current_organization.historical_data
    opts = {full_sync: full_sync}
    current_organization.sync_enabled = current_organization.synchronized_entities.values.any? { |settings| settings.values.any? { |v| v } }
    current_organization.enable_historical_data(params['historical-data'].present?)
    trigger_sync = current_organization.sync_enabled
    current_organization.save

    # Trigger sync only if the sync has been enabled
    start_synchronization(opts) if trigger_sync

    redirect_to(:back)
  end

  def synchronize
    return redirect_to(:back) unless is_admin
    Maestrano::Connector::Rails::SynchronizationJob.perform_later(current_organization.id, (params['opts'] || {}).merge(forced: true))
    flash[:info] = 'Synchronization requested'
    redirect_to(:back)
  end

  def redirect_to_external
    # If current user has a linked organization, redirect to the SalesForce instance url
    if current_organization && current_organization.instance_url
      redirect_to current_organization.instance_url
    else
      redirect_to 'https://www.shopify.com/login'
    end
  end

  private

    def start_synchronization(opts)
      Maestrano::Connector::Rails::SynchronizationJob.perform_later(current_organization.id, opts)
      flash[:info] = 'Congrats, you\'re all set up! Your data are now being synced' if current_organization.sync_enabled_changed?
    end
end

app/views/home/index.html.haml
.home
  .banners
    .row
      .col-md-10.col-md-offset-2
        %h2 Shopify Add-on
        %p
          -if current_organization
            Link your company <strong>#{current_organization.name} (#{current_organization.uid})</strong> to Shopify to get your business in synch. Check the status of your connection on this screen.

  .container
    - if session[:show_popup]
      - session[:show_popup] = false
      #modalCurrency.modal.fade{role: "dialog"}
        .modal-dialog
          .modal-content
            .modal-header
              %button.close{"data-dismiss" => "modal", :type => "button"}
              %h4.modal-title Warning!
            .modal-body
              - alert_msg
            .modal-footer
              %button.btn.btn-default{"data-dismiss" => "modal"} OK
      :javascript
        $('#modalCurrency').modal('show');
    - if current_user
      - unless is_admin
        .row
          .col-md-12.alert.alert-warning
            Only administrators can modify the application settings

      .row.link-step{class: "#{current_organization&.oauth_uid ? 'done' : 'todo'}"}
        .col-md-1.text-center.link-step-number
          %span.badge.link-step-badge
            1
        - if current_organization&.oauth_uid
          .col-md-6.link-step-description
            %h
              Your Shopify account <strong>#{current_organization&.oauth_name} (#{current_organization&.oauth_uid})</strong> is currently linked
          .col-md-2.col-md-offset-3.text-center.link-step-action
            = link_to "Disconnect",(is_admin ?  signout_omniauth_path(organization_id: current_organization&.id) : '#'), :disabled => !is_admin, class: "btn btn-warning btn-lg #{is_admin ? '' : 'disabled'}", rel: 'tooltip', title: "#{is_admin ? '' : 'You don\'t have the necessary rights to do this'}"
        - else
          %form#authentify-shopify.form-inline{:action => "/auth/shopify/request", :method => "GET" }
            .col-md-6
              %p Your Shopify account is not linked
              %p Please enter the “myshopify” domain of your store
              .form-group
                %label{:for => 'shop-name'}https://
                %input#shop-name{:name => "shop", :placeholder => 'your-store-1234', :type => 'text', :class => 'form-control', :disabled => !is_admin}
                %label .myshopify.com
                %input{:type=>"hidden", :value=>current_organization&.uid, :name=>:org_uid}/
            .col-md-2.col-md-offset-3.text-center.link-step-action
              %button{:type => "submit", :class => 'btn btn-warning btn-lg', :disabled => !is_admin, :rel => 'tooltip', :title => "#{is_admin ? '' : 'You don\'t have the necessary rights to do this'}"} Link to Shopify
              %br
              %small If you don’t have an account #{link_to 'create yours here', Maestrano::Connector::Rails::External.create_account_link(current_organization || nil)}


      .spacer1

      .row.link-step{class: "#{(current_organization&.sync_enabled && current_organization&.synchronized_entities.values.any?) ? 'done' : 'todo'}"}
        = form_tag home_update_path(id: current_organization&.id), method: :put do
          .col-md-1.text-center.link-step-number
            %span.badge.link-step-badge 2
          .col-md-9.link-step-description
            %p You can customize which entities are synchronized by the connector:
            %p (#{image_tag "logos/to_connec.png", class: "small-image"} : from Shopify to Connec! and #{image_tag "logos/to_external.png", class: "small-image"} : from Connec! to Shopify)
            .spacer1
            .row
              .col-md-11.col-md-offset-1.center
                .row
                  .col-md-1
                    =image_tag "logos/to_connec.png", class: "image"
                  .col-md-1
                    =image_tag "logos/to_external.png", class: "image"
                  .col-md-4
                    Shopify wording
                  .col-md-3
                    Universal wording
            .spacer1
            .row
              .col-md-11.col-md-offset-1
                - current_organization&.displayable_synchronized_entities&.each do |k, v|
                  .row.sync-entity
                    .col-md-1.link-step-action
                      #{check_box("#{k}", "to_connec", {checked: (v[:can_push_to_connec] || v[:can_push_to_external]) && !current_organization&.pull_disabled, onclick: "return !#{k}_to_external.checked;", disabled: current_organization&.pull_disabled})}
                    .col-md-1.link-step-action
                      #{check_box("#{k}", "to_external", {checked: v[:can_push_to_external] && !current_organization&.push_disabled, onchange: "#{k}_to_connec.checked = #{!current_organization&.pull_disabled};", disabled: current_organization&.push_disabled})}
                    %label.col-md-8{:for => "#{k}", style: 'padding-top: 5px;'}
                      .col-md-6
                        #{v[:external_name]}
                      .col-md-6
                        #{v[:connec_name]}
                    -if is_admin
                      .col-md-2.text-right
                        - if v && current_organization&.oauth_uid && current_organization&.sync_enabled && (current_organization&.synchronized_entities[k][:can_push_to_connec] || current_organization&.synchronized_entities[k][:can_push_to_external])
                          = link_to "Force a synchronization for #{k.to_s.humanize.pluralize} only", home_synchronize_path(opts: {only_entities: [k.to_s]}), method: :post, class: 'btn btn-warning btn-sm', 'data-toggle' => 'tooltip', 'data-placement' => 'right'

            / .spacer2
            / .row
            /   %h Chose whether to synchronize your historical data:
            .spacer2
            .row
              %p Chose whether to synchronize your historical data:
            .spacer1
            .row
              .col-md-4.col-md-offset-1
                Synchronize my historical data
              .col-md-1
                #myModal.modal.fade{:role => "dialog"}
                  .modal-dialog
                    .modal-content
                      .modal-header
                        %button.close{"data-dismiss" => "modal", :type => "button"} ×
                        %h4.modal-title Warning!
                      .modal-body
                        %p
                          %b All data
                          created prior to the date you linked Shopify
                          %b will be synchronised both ways.
                        %p
                          It means that:
                          %br
                          \- all data from applications you already have linked to the platform will be sent to your Shopify account
                          %br
                          \- all exisiting data from Shopify will be sent to your other applications
                          %br
                        %p
                          If you have been manually copying records in multiple applications,
                          %b you risk seeing duplicates arising!
                        %p
                          %b This action cannot be undone at any time!
                      .modal-footer
                        %button.btn.btn-primary{id: 'confirm', :type => "button", onclick: "closeModal(confirm);"}  Confirm
                        %button.btn.btn-secondary{id: 'close', :type => "button", onclick: "closeModal(close);"} Close
                %input{type: 'checkbox', id: 'historical-data', name: 'historical-data', checked: current_organization&.historical_data, onchange: 'historicalDataDisplay();', disabled: current_organization&.historical_data}
              .col-md-6
                %small#historical-data-display-unchecked{style: "display: #{current_organization&.historical_data ? 'none' : 'block'}"} Only data created or updated after #{(current_organization&.date_filtering_limit && current_organization&.date_filtering_limit.utc || Time.now.utc).to_formatted_s(:long_ordinal)} will be synchronized
                %small#historical-data-display-checked{style: "display: #{!current_organization&.historical_data ? 'none' : 'block'}"}
                  Synchronizing your historical data will share all data in Shopify. This action is not reversible. Want to know more? Check #{link_to 'here', 'https://maestrano.atlassian.net/wiki/display/UKB/How+Connec%21+manages+Historical+Data+Sharing'}

          .spacer1
          .row
            .col-md-2.col-md-offset-10.text-center.link-step-action
              =submit_tag "#{current_organization&.sync_enabled ? 'Update' : 'Start synchronizing!'}", class: "btn btn-lg btn-warning #{current_organization&.oauth_uid ? '' : 'disabled'} text-sm"

      -if current_organization&.oauth_uid && current_organization&.sync_enabled
        .spacer2
        .row
          .col-md-4.col-md-offset-4.text-center
            = link_to 'Go to Shopify', home_redirect_to_external_path, class: 'btn btn-lg btn-primary'