config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  mount Maestrano::Connector::Rails::Engine, at: '/'

  namespace :webhooks do
    post ':entity/:type/:org_uid' => :receive
  end

  # root 'home#index'
  root 'home#index'
  get 'home/index' => 'home#index'
  get 'home/redirect_to_external' => 'home#redirect_to_external'
  put 'home/update' => 'home#update'
  post 'home/synchronize' => 'home#synchronize'
  get 'synchronizations/index' => 'synchronizations#index'
  get 'shared_entities/index' => 'shared_entities#index'
  get 'admin/delete_webhooks' => 'home#delete_webhooks'


  match 'auth/:provider/request', to: 'oauth#request_omniauth', via: [:get, :post]
  match 'auth/:provider/callback', to: 'oauth#create_omniauth', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  match 'signout_omniauth', to: 'oauth#destroy_omniauth', as: 'signout_omniauth', via: [:get, :post]

  # Sidekiq Admin
  require 'sidekiq/web'
  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    ENV['SIDEKIQ_USERNAME'].present? &
    ActiveSupport::SecurityUtils.secure_compare(username, ENV['SIDEKIQ_USERNAME']) &
    ActiveSupport::SecurityUtils.secure_compare(password, ENV['SIDEKIQ_PASSWORD'])
  end
  mount Sidekiq::Web => '/sidekiq'
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Shopify Connector
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    %script{src: 'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js', integrity: 'sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa', crossorigin: 'anonymous'}
    = csrf_meta_tags
  %body
    .navbar.navbar-fixed-top.navbar-inverse
      .container-fluid
        .collapse.navbar-collapse#maestrano-navbar-collapse
          %ul.nav.navbar-nav
            =image_tag "logos/default.png", class: 'logo'

          %ul.nav.navbar-nav
            %li=link_to "Status", root_path

            %li=link_to "History", synchronizations_index_path

            -if is_admin
              %li=link_to "Mapping", shared_entities_index_path

          -if current_user
            %ul.nav.navbar-nav.navbar-right
              %li.dropdown
                %a{:href=>"#", :class=>"dropdown-toggle", :'data-toggle'=>"dropdown", :role=>"button"}
                  Hi #{current_user.first_name} #{current_user.last_name}

    .padding-navbar

    .wrapper{style: 'margin-bottom: 15px; '}
      - if flash.any?
        - flash.each do |flash_key, message|
          .alert{:class => "alert-#{flash_key}"}
            %strong= flash.discard(flash_key)

      = yield

    .footer
      .container
        .row
          .col-xs-12
            .copyright
              © Copyright #{Time.now.year}. All rights reserved. Various trademarks held by their respective owners.